name: Run PHPUnit

on:
  push:
      
jobs:
  run-phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', latest]
    steps:
      - uses: actions/checkout@v3

      - name: Run composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
          
      - name: Run tests
        uses: php-actions/phpunit@v3.0.0
        with:
          php_version: ${{ matrix.php-version }}
          configuration: phpunit.xml
